### ISSUE TITLE
Potential bug: multiple test cases causing other tests to not be executed properly.

### ISSUE THREAD

**Issue by zerowon01** [yoichiro/dialogflow-query-checker#21]
I assumed in using this test tool that I could define multiple rules for multiple intents, if that is a mistake in my understanding of the implementation then let me know and disregard this ticket. Otherwise, any help is appreciated.

What I saw: 
I've noticed that writing multiple test cases is causing tests to evaluate differently. Simply put:
1. I write a failing test. It fails as expected. 
2. Next, I write a second test and suddenly the first test (which should still fail) is passing. 
3. Lastly, I "break" the second test and only the second test shows as failing. So it seems like ONLY the last test is being evaluated properly. 
Additionally, I assumed that as my test cases grew there would be a longer processing time, but regardless of the number of tests the completion time was roughly the same, which furthers my suspicion.

I will share my test groups, the condition/expect pairs, and the resultant evaluations if necessary..

**Comment by yoichiro** [comment]
@zerowon01 Could you send me your yaml file, or post it here without sensitive data? I need to check your file because of understanding your situation more details.

**Comment by zerowon01** [comment]
Here are the excerpts that I prepared after my initial observations. They should give you an idea of the problem that I am observing. (Hopefully all the markdown looks readable.)

**Summary:**

**Test 1: (1) test case defined**
Result: Test #1 case is properly evaluated (failing condition prepared and test result reflects failing condition)

**Test 2: (2) test cases defined**
Result: Test case #1 is no longer evaluated correctly (failing condition defined, but result indicates "no problem"). Test case #2 evaluates correctly

------------------------------------------------------------
**Test Definitions**:
`
#Test 1(note: second test case is commented out) ==============================

    ##Test case 1: Default fallback intent through nonsense? ------------------------------------------------
    condition:
      query: "Elbow srwjk etats camelCase envious rabbit?" 
    expect:
      intentName: "Default Fallback Intent"
      speeches:
        - "nerf"
        #- "(?i)what was that|missed what|what did you say|missed that|say that again|didn't get that|one more time|missed that"
      endConversation: true
`
**Evaluation**:
...F.
Query: Elbow srwjk etats camelCase envious rabbit?
  Failure: speech is not matched to expected regular expression.
    Expected: "nerf"
    Actual: What was that?
Finished in 0.539504 seconds.
1 test failed.


Test  2 (note: the first two test cases are uncommented)
`
#Test case #1 Default fallback intent? 
    condition:
      query: "Elbow srwjk etats camelCase envious rabbit?" 
    expect:
      intentName: "Default Fallback Intent"
      speeches:
        - "nerf"
        #- "(?i)what was that|missed what|what did you say|missed that|say that again|didn't get that|one more time|missed that"
      endConversation: true
`

`
    #Test case # 2 Who are you? ------------------------------------------------
    condition:
      query: "Who are you?" 
    expect:
      action: "smalltalk.introduction"
      intentName: "smalltalk.introduction"
      speeches:
        - "^Gaia.*"
      endConversation: true
`
**Evaluation**:
.....
Finished in 0.361002 seconds.
All tests **passed**.

I would expect that my first test is still failing.
Furthermore two tests takes less time than one (more like the mean test execution time varies around a value that doesn't change regardless of the number of tests included.

**Comment by yoichiro** [comment]
@zerowon01 I guess that this issue is same as https://github.com/yoichiro/dialogflow-query-checker/issues/19#issuecomment-370305019.

**Comment by yoichiro** [comment]
@zerowon01 The original format you wrote is:

```yaml
...
tests:
  -
    #Default fallback intent? ------------------------------------------------
    condition:
      query: "Elbow srwjk etats camelCase envious rabbit?" 
    expect:
      action: "input.unknown"
      intentName: "Default Fallback Intent"
      speeches:
        - "nerf"
        #- "(?i)what was that|missed what|what did you say|missed that|say that again|didn't get that|one more time|missed that"
      endConversation: true
    
    #Who are you? ------------------------------------------------
    condition:
      query: "Who are you?" 
    expect:
      action: "smalltalk.introduction"
...
```

The correct code is the following:

```yaml
...
tests:
  -
    #Default fallback intent? ------------------------------------------------
    condition:
      query: "Elbow srwjk etats camelCase envious rabbit?" 
    expect:
      action: "input.unknown"
      intentName: "Default Fallback Intent"
      speeches:
        - "nerf"
        #- "(?i)what was that|missed what|what did you say|missed that|say that again|didn't get that|one more time|missed that"
      endConversation: true
  -    
    #Who are you? ------------------------------------------------
    condition:
      query: "Who are you?" 
    expect:
      action: "smalltalk.introduction"
...
```
